LAB_DESCRIPTION="Three Floor LAN based Network"
LAB_VERSION=1.0
LAB_AUTHOR="Dhimas Bagus Rizky Dewanto, Edi Permadi, Muhammad Zuhdi Afi Abiyyi"
LAB_WEB=https://github.com/edipermadi/network-and-cybersecurity-aol

# ===================
# Level 1 PC
# ===================
level1_pc[image]="kathara/base"
level1_pc[0]="level1_lan"
level1_pc[ipv6]="false"

# ===================
# Level 1 Switch
# ===================
level1_switch[image]="kathara/base"
level1_switch[0]="level1_lan"
level1_switch[1]="level1_link"
level1_switch[ipv6]="false"

# ===================
# Level 1 Router
# ===================
level1_router[image]="kathara/base"
level1_router[0]="level1_link"
level1_router[1]="edge_lan_1"
level1_router[ipv6]="false"

# ===================
# Level 2 PC
# ===================
level2_pc[image]="kathara/base"
level2_pc[0]="level2_lan"
level2_pc[ipv6]="false"

# ===================
# Level 2 Switch
# ===================
level2_switch[image]="kathara/base"
level2_switch[0]="level2_lan"
level2_switch[1]="level2_link"
level2_switch[ipv6]="false"

# ===================
# Level 2 Router
# ===================
level2_router[image]="kathara/base"
level2_router[0]="level2_link"
level2_router[1]="edge_lan_2"
level2_router[ipv6]="false"

# ===================
# Level 3 PC
# ===================
level3_pc[image]="kathara/base"
level3_pc[0]="level3_lan"
level3_pc[ipv6]="false"

# ===================
# Level 3 Switch
# ===================
level3_switch[image]="kathara/base"
level3_switch[0]="level3_lan"
level3_switch[1]="level3_link"
level3_switch[ipv6]="false"

# ===================
# Level 3 Router
# ===================
level3_router[image]="kathara/base"
level3_router[0]="level3_link"
level3_router[1]="edge_lan_3"
level3_router[ipv6]="false"

# ===================
# Edge Switch
# ===================
edge_switch[image]="kathara/base"
edge_switch[0]="edge_lan_1"
edge_switch[1]="edge_lan_2"
edge_switch[2]="edge_lan_3"
edge_switch[3]="edge_link"
edge_switch[ipv6]="false"

# ===================
# Edge Router
# ===================
edge_router[image]="kathara/base"
edge_router[0]="edge_link"
edge_router[1]="public_internet"
edge_router[ipv6]="false"

# ===================
# Simulated Internet
# ===================
internet[image]="kathara/base"
internet[0]="public_internet"
internet[ipv6]="false"