LAB_DESCRIPTION="Three Floor LAN based Network"
LAB_VERSION=1.0
LAB_AUTHOR="Dhimas Bagus Rizky Dewanto, Edi Permadi, Muhammad Zuhdi Afi Abiyyi"
LAB_WEB=https://github.com/edipermadi/network-and-cybersecurity-aol

# Local Tier
pc[0]="local_lan/00:00:00:00:06:01"

# ===================
# Local Switch
# ===================
local_router[image]="kathara/base"
local_switch[0]="local_lan/00:00:00:00:05:01"
local_switch[1]="local_link/00:00:00:00:05:02"
local_switch[ipv6]="false"

# ===================
# Local Router
# ===================
local_router[image]="kathara/base"
local_router[0]="local_link/00:00:00:00:04:01"
local_router[1]="edge_lan/00:00:00:00:04:02"
local_switch[ipv6]="false"

# ===================
# Edge Switch
# ===================
edge_switch[image]="kathara/base"
edge_switch[0]="edge_lan/00:00:00:00:03:01"
edge_switch[1]="edge_link/00:00:00:00:03:02"
edge_switch[ipv6]="false"

# ===================
# Edge Router
# ===================
edge_router[image]="kathara/base"
edge_router[0]="edge_link/00:00:00:00:02:01"
edge_router[1]="public_internet/00:00:00:00:02:02"
edge_router[ipv6]="false"

# ===================
# Simulated Internet
# ===================
internet[image]="kathara/base"
internet[0]="public_internet/00:00:00:00:01:01"
internet[ipv6]="false"