LAB_DESCRIPTION="Three Floor LAN based Network"
LAB_VERSION=1.0
LAB_AUTHOR="Dhimas Bagus Rizky Dewanto, Edi Permadi, Muhammad Zuhdi Afi Abiyyi"
LAB_WEB=https://github.com/edipermadi/network-and-cybersecurity-aol

# PC to Switch (Private Domain)
pc[0]="A"
switch[0]="A"

# Switch to Router (Private Domain)
switch[1]="C"
router[0]="C"

# Router to Internet (Public Domain)
router[1]="B"
internet[0]="B"
